// <auto-generated />
using System;
using DataPumper.Web.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataPumper.Web.Migrations
{
    [DbContext(typeof(DataPumperContext))]
    [Migration("20200422152249_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("DataPumper.Web.DataLayer.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DataPumper.Web.DataLayer.SyncJobLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Elapsed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableSyncJobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TableSyncJobId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DataPumper.Web.DataLayer.TableSyncJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TableSyncJobs");
                });

            modelBuilder.Entity("DataPumper.Web.DataLayer.SyncJobLog", b =>
                {
                    b.HasOne("DataPumper.Web.DataLayer.TableSyncJob", "TableSyncJob")
                        .WithMany("Log")
                        .HasForeignKey("TableSyncJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
