// <auto-generated />
namespace Quirco.DataPumper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Actuality : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Actuality));
        
        string IMigrationMetadata.Id
        {
            get { return "202007160618187_Actuality"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
