// <auto-generated />
namespace Quirco.DataPumper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddLastQuery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLastQuery));
        
        string IMigrationMetadata.Id
        {
            get { return "202007152249285_Add-LastQuery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
