name: publish to nuget 

on: 
  push:
    tags:
        - "v*"

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get the tag version
        id: get_version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/v}
        shell: bash
        
      - name: Tag version
        run: echo ${{ steps.get_version.outputs.SOURCE_TAG }}
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: 'latest'

      - run: msbuild -t:restore
        working-directory: src/Quirco.DataPumper
        
      - run: msbuild -t:build -p:Configuration=Release -p:PackageVersion=${{ steps.get_version.outputs.SOURCE_TAG }}
        working-directory: src/Quirco.DataPumper
      - name: Nuget SetAPIKey
        run: nuget setapikey ${{ secrets.NUGET_API_KEY }}
      - name: Publish the package to nuget.org
        working-directory: src/Quirco.DataPumper
        run: nuget push bin\debug\*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate
